FROM python:3.6.5-jessie

# install environment dependencies: 
# if netcat is not installed, entrypoint.sh will not run
RUN apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends netcat \
  && apt-get -q clean


# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add requirements
COPY ./requirements.txt /usr/src/app/requirements.txt

# install requirements
RUN pip install -r requirements.txt

# add app
COPY . /usr/src/app

# add entrypoint.sh
COPY ./entrypoint-prod.sh /usr/src/app/entrypoint-prod.sh
RUN chmod +x ./entrypoint-prod.sh

# run server
CMD ["./entrypoint-prod.sh"]