"""empty message

Revision ID: 605bd9eff185
Revises: 31d9d0b1bd04
Create Date: 2018-06-07 19:47:32.354689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '605bd9eff185'
down_revision = '31d9d0b1bd04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=255)))
    op.execute('UPDATE users SET password=email')
    op.alter_column('users', 'password', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
