FROM node:10.4

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

COPY package.json /usr/src/app/package.json
RUN yarn install --silent
RUN yarn add react-scripts@1.1.4 -g --silent

CMD ["yarn", "start"]